default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: novo_caminho_app_development

test:
  <<: *default
  database: novo_caminho_app_test

production:
  <<: *default
  database: novo_caminho_app_production
  username: novo_caminho_app
  password: <%= ENV["NOVO_CAMINHO_APP_DATABASE_PASSWORD"] %>
